import Head from 'next/head'

import { useState } from 'react';
import { useSelector } from 'react-redux';
import CourseList from '../components/courses/CourseList';
import Header from '../components/header/Header';
import { getSelectedCourses } from '../store/selectedSelector';

export default function Courses() {

  const [courses, setCourses] = useState('');
  const selected = useSelector(getSelectedCourses);
  console.log(selected);

  return (
    <div className='bg-gray-100 w-screen h-screen'>
        <Head>
            <title>uniELTE | Kurzusaim</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className='md:px-5 md:pb-5'>
            <Header />
            <CourseList courses={selected} selected={selected} mylist={true}/>
        </div> 
    </div> 
  )
}