import Head from 'next/head'

import { useState } from 'react';
import SearchBar from '../components/Searcbar'
import CourseList from '../components/courses/CourseList';
import Header from '../components/header/Header';

export default function Search() {

  const [courses, setCourses] = useState('');
  const [selected, setSelected] = useState([]);

  return (
    <div className='bg-gray-100 w-screen h-screen'>
        <Head>
            <title>uniELTE | Keresés</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className='md:px-5 md:pb-5'>
            <Header />
            <SearchBar setCourses={setCourses}/>
            <CourseList courses={courses} selected={selected} setSelected={setSelected} mylist={false}/>
        </div> 
    </div> 
  )
}