import Head from 'next/head'

import { useState } from 'react';
import SearchBar from '../components/Searcbar'
import TimeTable from '../components/timetable/TimeTable';
import Header from '../components/header/Header';
import { useSelector } from 'react-redux';
import { getSelectedCourses } from '../store/selectedSelector';

export default function Timetable() {

  const [courses, setCourses] = useState('');
  const selected = useSelector(getSelectedCourses);


  const createTask = (course) => {
    let date = course.Idopont.split(' ');
    let day = date[0];
    let time = date[1].split('-');
    let fromTime = time[0];
    let toTime = time[1];
    
    return {
      'type': course.Oratipus,
      'code': course.Csop,
      'subject': course.Kurzusnev,
      'teacher': course.Oktato,
      'place': course.Helyszin,
      'day': day,
      'from': {
        'hour': fromTime.split(':')[0],
        'minute': fromTime.split(':')[1]
      }, 
      'to': {
        'hour': toTime.split(':')[0],
        'minute': toTime.split(':')[1]
      }
    }
  } 

  const createTaskList = (selected) => {
    return selected.filter(s => s.Idopont !== undefined).map(s => createTask(s));
  }

  return (
    <div className='bg-gray-100 w-screen h-screen'>
        <Head>
            <title>uniELTE | Órarend</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className='md:px-5 md:pb-5'>
            <Header />
            <SearchBar setCourses={setCourses}/>
            <TimeTable data={createTaskList(selected)}/>
        </div> 
    </div> 
  )
}