name: Deploy to firebase

on:
  release:
    types:
      - published

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    - name: Setup the code
      run: npm install
    - name: Deploy to Firebase
      uses: mohammed-atif/firebase-publish-react@v1.0
      with:
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}
